# Generated by Django 5.2.1 on 2025-05-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1. Biodata'},
        ),
    ]
